# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BE0KQ4OlHbR-jryk4tRBbLLvZDCr3wHE
"""

calificaciones = []
nombres = []
algo =[]
def fng(calificaciones, nombres):
  cal = []
  for i in range(10):
    print("ingrese la calificacion")
    calif2 = float(input())
    calificaciones.append(calif2)
    print("ingrese su nombre")
    nomb2 = str(input())
    nombres.append(nomb2)
    if (calificaciones[i] >= 8.5):
      algo.append(nombres[i])
  return (algo)
print ("los alumnos que tienen promedio de 8.5 son: ", fng(calificaciones, nombres))