# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KhSu0NS8tSAHQa2Syg4xTWRPyWPGzLpI
"""

edades = []
mayores = 0
menores = 0
def leer(edades):
  for i in range(10):
    print("Ingrese su edad")
    edades.append(int(input()))

def maxymen(edades, mayores, menores):
  for i in range(len(edades)):
    if (edades[i] >= 18):
      mayores = mayores+1
    else:
      menores = menores+1
  return mayores, menores

def imprimir (mayores, menores):
  print ("los mayores son:", mayores)
  print ("los menores son:", menores)

leer(edades)
mayores, menores = maxymen(edades, mayores, menores)
imprimir(mayores, menores)