# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uNkNlCKQ8JWgQc1acCCdbg_wyxhV2uKx
"""

# Crear una lista
L = ["The Bodyguard", 7.0, 1992]
L

# Imprime los elementos en cada índice

print('el mismo elemento usando indexación negativa y positiva:\n Positivo:',L[0],
'\n Negativo:' , L[-3]  )
print('el mismo elemento usando indexación negativa y positiva:\n Positivo:',L[1],
'\n Negativo:' , L[-2] )
print('el mismo elemento usando indexación negativa y positiva:\n Positivo:',L[2],
'\n Negativo:' , L[-1] )

# Lista de muestra

["The Bodyguard", 7.0, 1992, [1, 2], ("A", 1)]

# Lista de muestra

L = ["The Bodyguard", 7.0,1992,"BG",1]
L

# Segmentación de listas

L[3:5]

# Use extender para agregar elementos a la lista

L = [ "The Bodyguard", 7.0]
L.extend(['pop', 10])
L

# Usar append para agregar elementos a la lista

L = [ "The Bodyguard", 7.0]
L.append(['pop', 10])
L

# Use extender para agregar elementos a la lista

L = [ "The Bodyguard", 7.0]
L.extend(['pop', 10])
L

# Usar append para agregar elementos a la lista

L.append(['a','b'])
L

# Cambiar el elemento en función del índice

A = ["disco", 10, 1.2]
print('Before change:', A)
A[0] = 'hard rock'
print('After change:', A)

# Eliminar el elemento en función del índice

print('Before change:', A)
del(A[0])
print('After change:', A)

# Divida la cadena, el valor predeterminado es por espacio

'hard rock'.split()

# Dividir la cadena por coma

'A,B,C,D'.split(',')

# Copiar (copiar por referencia) la lista A

A = ["hard rock", 10, 1.2]
B = A
print('A:', A)
print('B:', B)

# Examinar la copia por referencia

print('B[0]:', B[0])
A[0] = "banana"
print('B[0]:', B[0])

# Clonar (clonar por valor) la lista A

B = A[:]
B

print('B[0]:', B[0])
A[0] = "hard rock"
print('B[0]:', B[0])

#Cree una lista a_list, con los siguientes elementos 1, hello, [1,2,3] y True.
a_list=[1, "hello", [1, 2, 3], True]
a_list

#Encuentre el valor almacenado en el índice 1 de a_list.
print (a_list[0])

#Recupere los elementos almacenados en el índice 1, 2 y 3 de a_list.
print(a_list[1:4])