# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BE0KQ4OlHbR-jryk4tRBbLLvZDCr3wHE
"""

calificaciones = []
algo = 0
def fng(calificaciones, sum):
  cal = []
  for i in range(10):
    print("ingrese la calificacion")
    calif2 = float(input())
    calificaciones.append(calif2)
    if (calif2 >= 8.5):
      sum=sum+1
  return (sum)
print ("los alumnos que tienen promedio de 8.5 son: ", fng(calificaciones, sum))