# -*- coding: utf-8 -*-
"""Copia de Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fv3IPthMEUhmjzljR34_ZJ-OcOsR1E6S
"""

d1 = {
    "nombre": "Oli Didier Mendoza Siordia",
    "matricula": "241690414-8",
    "edad": "16",
    "peso": "85",
    "telefono": "3841009646",
    "domicilio": "Jalisco 221",
    "carrera": "CDIA"
}

for x, y in d1.items():
  print(x, y)
#para modificar sus elementos basta con escribir el nombre del diccionario seguido por el nombre de la llave entre corchetes y comillas de esta forma [""] y agregar un "="
#después del igual escribir el elemento que se desea reescrir
#ejemplo d1["edad"] = "18"