# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FijWl6pEhZS2eP8pZbS30O3Er3q4KJRD
"""

trabajador = []
salario = []
nomina = 0
trab3 = 0
sal = 0
trab2 = 0
algo = 0
def leer(trabajador, salario):
  for i in range(5):
    print ("dime tu nombre")
    trab2=(input())
    trabajador.append(trab2)
    print ("dime tu salario")
    sal=float(input())
    salario.append(sal)

def cosa1(trabajador, salario):
  nomina = 0
  algo = 0
  trabajador_mayor_salario = ""
  for i in range(len(salario)):
    nomina = nomina + salario[i]
    if (salario[i] > algo):
      algo = salario[i]
      trabajador_mayor_salario = trabajador[i]
  return nomina, algo, trabajador_mayor_salario

def cosa2(nomina, algo, trabajador_mayor_salario):
  print ("la nomina es de: ", nomina)
  print ("el trabajador que más gana es: ", trabajador_mayor_salario,)
leer(trabajador, salario)
nomina_total, salario_maximo, trabajador_maximo = cosa1(trabajador, salario)
cosa2(nomina_total, salario_maximo, trabajador_maximo)