# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15DxkRCZbU-q4z_O0GWVvY0qCWG2Rn3VL
"""

temp_f= [80, 72, 95, 82, 79, 72, 85]
temp_c= []
for i in temp_f:
  temp_c.append((i-32) * 5/9)
for x in temp_c:
  print (x)